version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: vaadin
      POSTGRES_PASSWORD: vaadin
      POSTGRES_DB: vaadin
